### ISSUE TITLE
TypeError: Cannot read property 'local' of undefined

### ISSUE THREAD

**Issue by frejfrej** [reywood/bitbucket-pr-review#1]
Hi!

Just installed your plugin on Chrome latest and got the following issue:

Uncaught (in promise) TypeError: Cannot read property 'local' of undefined
    at Promise (dataStore.js:57)
    at new Promise (<anonymous>)
    at Function.[set] (dataStore.js:56)
    at Function.setReviewed (dataStore.js:14)
    at FileDiff.setReviewed (fileDiff.js:50)
    at <anonymous>
Promise @ dataStore.js:57
[set] @ dataStore.js:56
setReviewed @ dataStore.js:14
setReviewed @ fileDiff.js:50
async function (async)
setReviewed @ fileDiff.js:48
[handleButtonClick] @ fileDiff.js:95
btn.addEventListener @ fileDiff.js:68

Any hint as to what I should do to make it work?

**Comment by reywood** [comment]
Hmm, that's odd. What version of Chrome are you using?

**Comment by frejfrej** [comment]
Well, sorry I bothered: restarting Chrome made it work like a charm.

Thanks you so much for this extension... This is just everything I (and all reviewers around me) ever dreamt of!!
