### ISSUE TITLE
Files with spaces in their path don't collapse

### ISSUE THREAD

**Issue by timbeadle** [reywood/bitbucket-pr-review#13]
* Files with ~~.sql extension~~ spaces in their file paths don't collapse when the Done Reviewing button is pressed

**Comment by kthompson** [comment]
I have noticed that I have one file in particular that won't collapse and it is a `.json` file. It has spaces in it. Not sure if you have the same for your SQL files.

**Comment by timbeadle** [comment]
@kthompson Good spot. It's not .sql files as such, just files with spaces in the file path. Thanks!

**Comment by timbeadle** [comment]
Duplicate of #9

**Comment by reywood** [comment]
This is fixed in latest release. Thank you @kthompson for figuring out the issue!
