### ISSUE TITLE
Could "Done Reviewing" button also be displayed below the file?

### ISSUE THREAD

**Issue by MaartenLapere** [reywood/bitbucket-pr-review#15]
I often scroll through a file to the bottom, and then have to scroll all the way up again to mark it as done. This gets tedious for long files. Could the button be moved to below the file? Or duplicated there?

**Comment by reywood** [comment]
I feel your pain. I’ve been meaning to do this but haven’t gotten around to it yet.

**Comment by utapyngo** [comment]
I often scroll from bottom to top, so I want this button in both places.

**Comment by reywood** [comment]
This feature has been added in v1.6.0.
