### ISSUE TITLE
Publish extension to Firefox addons store

### ISSUE THREAD

**Issue by kthompson** [reywood/bitbucket-pr-review#16]
I manually loaded this plugin into firefox and it seems to work fine. Would be nice to be able to get it from the Firefox addons page: https://addons.mozilla.org/en-US/firefox/

**Comment by reywood** [comment]
I'll look into this when I have some time

**Comment by reywood** [comment]
Finally got some time. Published!

**Comment by kthompson** [comment]
Awesome thanks 👍

**Comment by kthompson** [comment]
I could not find the addon in the firefox store could you link it? Might be good to add to the README also.

**Comment by kthompson** [comment]
nevermind I found it. Thanks again.
