### ISSUE TITLE
Very large pull requests display previously reviewed files as unreviewed

### ISSUE THREAD

**Issue by utapyngo** [reywood/bitbucket-pr-review#18]
When opening a large pull request, some files are not loaded. 
There is a button "Load all failed diffs" added by [Redefined Bitbucket][1].
After loading all failed files, they all are displayed as unreviewed.
When a new change is detected in PR, and the notification "Pull request updated" in the bottom-right corned appears, all files become displayed correctly.

[1]: https://chrome.google.com/webstore/detail/refined-bitbucket/afppminkfnfngihdocacbgeajbbdklkf

**Comment by reywood** [comment]
I believe the newest release probably fixes this issue. I'm going to close this issue, but if you find that it isn't fixed, then let me know and I'll reopen.
