### ISSUE TITLE
Need help with internationalization (i18n)

### ISSUE THREAD

**Issue by reywood** [reywood/bitbucket-pr-review#25]
I was checking out the stats for this extension on the Firefox Add-ons store and noticed that we have some international users. I thought it'd be nice if they could use this extension in their native language. If anyone is fluent (or at least semi-fluent) in a language other than English, I'd greatly appreciate your help with translations.

The following languages appear in the Firefox stats, so they are a good place to start:

* ~~French (fr)~~
* ~~German (de)~~
* ~~Polish (pl)~~
* ~~Russian (ru)~~
* ~~Spanish (es)~~
* ~~Turkish (tr)~~

To add a new language, create a new directory under the `_locales` directory with the [locale code](https://developer.chrome.com/webstore/i18n#localeTable) as the name (e.g. `fr` for French, `de` for German, etc). Then, copy the `messages.json` file from the `en` directory and modify the `message` values with the correct translation. For example, if you were creating a French translation, your new file would be located at `_locales/fr/messages.json`. You can remove the `description` fields from this new file as they are not needed.

You can find more info about how browser extension internationalization works [here](https://developer.chrome.com/webstore/i18n) and [here](https://developer.chrome.com/extensions/i18n).

**Comment by karorogunso** [comment]
Hey, I just add the Thai Language for you.

Enjoy mate. : )

**Comment by wait-what** [comment]
I'll add Lithuanian

**Comment by vherasme** [comment]
I have sent #31

**Comment by insertish** [comment]
I translated to Polish #35
