### ISSUE TITLE
Make PR Review Helper work with the new PR review experience.

### ISSUE THREAD

**Issue by epicserve** [reywood/bitbucket-pr-review#37]
This browser extension stopped working when I switched to the new [PR review experience](https://confluence.atlassian.com/bitbucket/the-new-pull-request-experience-in-bitbucket-958455255.html).

**Comment by reywood** [comment]
The new PR interface has a built in way to collapse files via a little down arrow chevron on the left side of each file's header. I'm not sure it's worth it to try to port this extension to the new interface. Thoughts?

**Comment by epicserve** [comment]
@reywood, right but it doesn't save where you were at ... so if you close the tab or refresh it starts over. I do understand your thought that it might not be worth it. It's also on the list of things they want to add natively, but who knows how long that will take. They still don't have syntax highlighting! 😜

I just thought if it wasn't that hard to do that it would be a nice stop-gap solution.

**Comment by reywood** [comment]
Hmm, it remembers the state for me. If I collapse a few files and reload, those files are still collapsed. Maybe that's a feature they're rolling out slowly?

**Comment by epicserve** [comment]
Could be ... strange it seems to be remembering now.

BTW, for anyone that's interested here is their issue for adding it natively.

https://jira.atlassian.com/browse/BCLOUD-19679
