### ISSUE TITLE
JS error when marking files are revirwed

### ISSUE THREAD

**Issue by chai-deshpande** [reywood/bitbucket-pr-review#9]
![image](https://user-images.githubusercontent.com/5366467/35526252-bcfcbe5c-051e-11e8-85c1-d2a55099dd6b.png)

Please see the call stack of the exception while clicking the "Done Reviewing" button.

**Comment by VictorQRS** [comment]
This is also happening to me. Is there any progress regarding this issue?

**Comment by timzap** [comment]
The error occurs when the path to a file (including the filename) has a space in it.

**Comment by timbeadle** [comment]
@timzap That makes #13 a duplicate of this issue, then.

**Comment by reywood** [comment]
Thanks to @timzap for the PR. Finally got this merged and put a new version up.
